"""add_avatar_url_to_users

Revision ID: 432850e4cb2b
Revises: 27ad28e85bb5
Create Date: 2026-09-30 11:02:48.813544

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '432850e4cb2b'
down_revision: str | Sequence[str] | None = '27ad28e85bb5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'users', sa.Column('avatar_url', sa.String(length=1024), nullable=True)
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###
